[build]
  command = "npm run build"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/v1/api/*"
  status = 200
  to = "/v1/api/:splat"